mutation MyCartLinesAdd($input: [CartLineInput!]!) {
  cartLinesAdd(cartId: "gid://shopify/Cart/d0e5a930f77cfc01bb0ec138b9b5dfeb", lines: $input) {
    cart {
      id
        lines(first:2){
        edges{
           node{
            quantity
            merchandise {
              ... on ProductVariant {
                product{
                  handle
                  title
                  priceRange{
                    maxVariantPrice{
                      amount
                    }
                  }
                }
              }
            }
          }
        }
      }