mutation cartLinesAdd($input: [CartLineInput!]!) {
  cartLinesAdd($id: ID!, $lines: [CartLineUpdateInput!]!) {
    cart {
      id
        lines(first:2){
        edges{
           node{
            quantity
            merchandise {
              ... on ProductVariant {
                product{
                  handle
                  title
                  priceRange{
                    maxVariantPrice{
                      amount
                    }
                  }
                  images(first: 1) {
                    edges {
                      node {
                        url
                        altText
                      }
                    }
                  }
                  
                }
              }
            }
          }
        }
      }