mutation cartLinesUpdate($id: ID!, $lines: [CartLineUpdateInput!]!) {
  cartLinesUpdate(cartId: $id, lines: $lines) {
    cart {
      id
      lines(first: 5) {
        edges {
          node {
            quantity
            merchandise {
              ... on ProductVariant {
                product {
                  handle
                  title
                  priceRange {
                    maxVariantPrice {
                      amount
                    }
                  }
                  images(first: 1) {
                    edges {
                      node {
                        url
                        altText
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    userErrors {
      field
      message
    }
  }
}
