import Head from "next/head";
import HeroCarrousel from "./Components/Main/HeroCarrousel";
import HeroHeather from "./Components/Main/HeroHeather";
import Form from "./Components/Main/Form";

export default function Home() {
  return (
    <div>
      <Head>
        <title>CrochetMx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroHeather />
      <HeroCarrousel />
      <Form />
    </div>
  );
}
