import Head from 'next/head'
import { useState } from 'react'
import { NavBar } from './Components//NavBar/NavBar'
import Main from './Main'

export default function Home() {
  const [show, setShow] = useState(false)
  return (
    <div>
      <Head>
        <title>CrochetMx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar show={show} setShow={setShow}/>
      <Main show={show}/>

    </div>
  )
}
